### ISSUE TITLE
Better message for manual intervention

### ISSUE THREAD

**Issue by igorkulman** [Lightricks/Kintsugi#103]
Trying to to solve merge conflicts today I got this

```
A merge conflict that needs manual intervention occurred: Trying to change value of attribute named 'version from '' to '3.4.0', but the existing value is ''. Choose one: (Press ↑/↓ arrow to move and Enter to select)
‣ Set to new value ''
  Keep existing value ''
  Abort
```

I think this is quite confusing, I do not really know what the `version` attribute is related to. Best guess is SPM but in the file there was no "3.4.0" string anywhere.

The options are also confusing, they look the same, keeping and empty string vs setting it to the same empty string?

I chose the first option and it resulted in duplicated SPM dependency, I had to fix it manually in Xcode.

I think this message and option require a better explanation to know what they are actually related to.

**Comment by byohay** [comment]
Hi!
I'm just guessing, but maybe `3.4.0` was taken from "theirs" version of the project, and after choosing an option Kintsugi chose not to include it(?) 
Regardless, the options are not very informative and I suspect it's actually a bug. 
Is there any chance you can reproduce this?

**Comment by igorkulman** [comment]
Sorry, I tried reproducing but I was not able to. I think the conflict was when the same SPM package was once on tje project without a fixed version and once with a fixed version but I tried it and did not get the problem again.
