### ISSUE TITLE
Bad handling of files with the same name in different targets

### ISSUE THREAD

**Issue by nathansalaun-sofia** [Lightricks/Kintsugi#104]
I've had this case happen twice in my project now. Basically when there are two files of the same name BUT compiled in two different targets, Kintsugi will put all targets in one file and leave none on the other.

So let's say that I have the following files:
- SomeFolder/MySwiftFile.swift -> TargetA, TargetB
- SomeOtherFolder/MySwiftFile.swift -> TargetC

When resolving merge conflicts, Kintsugi will change the targets to be the following:
- SomeFolder/MySwiftFile.swift -> TargetA, TargetB, TargetC
- SomeOtherFolder/MySwiftFile.swift -> No targets

Which wrecks havoc in the project.

I don't have a clear way to reproduce it but it happened to me twice already.

**Comment by byohay** [comment]
I tried to reproduce this by creating two targets that have two files with the same name but it behaved correctly. I also tried using two targets that point to one file and another that points to another file with the same name, but it also worked.
Are you sure you're using the latest version? I remember we solved something around this in one of the previous versions.

**Comment by byohay** [comment]
ok, found the issue. The problem is that the diff doesn't contain information about which file should be used by the build file. I can make an heuristic that would select the file without any build file if such exists, and otherwise takes the first one. It's not foolproof, but it will help in your case.
