### ISSUE TITLE
 undefined method `configuration_list'

### ISSUE THREAD

**Issue by codyrotwein** [Lightricks/Kintsugi#111]
When running Kintsugi, I'm getting the following error:
`/Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.3/lib/kintsugi/apply_change_to_project.rb:457:in `child_component': undefined method `configuration_list' for <PBXNativeTarget name=`MyApp` UUID=`8B0F7A522A991C9A00233F44`>:Xcodeproj::Project::Object::PBXNativeTarget (NoMethodError)
Did you mean?  configure_with_plist`

Any ideas on how to resolve?

**Comment by byohay** [comment]
@codyrotwein I wasn't able to reproduce it yet, what version of Xcode are you using? 
Additionally, can you post the diff by running kintsugi with `--changes-output-path`?

**Comment by codyrotwein** [comment]
@byohay Xcode 15.0.1. I ended up just manually correcting the git merge conflicts. You can probably close the issue since I don't have the merged branch anymore and therefore can't debug with you further on the issue. Thanks though.

**Comment by byohay** [comment]
Makes sense. 
I don't think I've ever seen `configuration_list` under `native_target` before, so I thought it might be related to a newer Xcode version. Let's see if it happens again..

**Comment by luco** [comment]
Getting the same here, with Xcode 15.
