### ISSUE TITLE
(null) instead of BuildFile 

### ISSUE THREAD

**Issue by igorkulman** [Lightricks/Kintsugi#131]
I noticed that sometimes when I use Kintsugi it changes `(null)` to `BuildFile`

![Screenshot 2024-11-28 at 19 05 28](https://github.com/user-attachments/assets/4598f8b2-07bd-427d-a6bf-d1e5a6b3cfbd)

Which by itself is fine I guess but when I add a new file to the project Xcode just changes it back to `BuildFile` creating unnecessary noise of changing project file lines back and forward.

**Comment by barakwei** [comment]
I believe this was fixed a few versions ago, what version are you running?

**Comment by igorkulman** [comment]
You are right, I was not on the latest version.
