### ISSUE TITLE
Bundler could not find compatible versions for gem "xcodeproj"

### ISSUE THREAD

**Issue by HormyAJP** [Lightricks/Kintsugi#27]
Using the latest cocopods gem (1.11.2) causes a conflict in xcodeproj with kintsugi:

```
cocoapods (= 1.11.2) was resolved to 1.11.2, which depends on
      xcodeproj (>= 1.21.0, < 2.0)
kintsugi was resolved to 0.3.0, which depends on
      xcodeproj (= 1.19.0)
```

**Comment by byohay** [comment]
Hey @HormyAJP! The reason why Kintsugi depends on a specific xcodeproj version, is that the `project_diff` that Kintsugi relies on is not part of their API (Or at least that's how I understand it). I don't have a long term solution, but if Kintsugi works with 1.21 I can relax the requirements a bit.
Maybe the long term solution is just to make our own `project_diff` function.

**Comment by HormyAJP** [comment]
@byohay thanks for the response. I don't know enough about the project I'm afraid to comment. It looks like #28 fixed the issue for now. If this comes back to bite later then I'd be potentially interested in helping contribute a fix.

**Comment by byohay** [comment]
@HormyAJP thanks! Hope it works now :)
