### ISSUE TITLE
Fails when ????.xcodeproj has space in name

### ISSUE THREAD

**Issue by pryder-fleetaero** [Lightricks/Kintsugi#41]
Hi,

The tool appears to fail when the there's a space in the ".xcodeproj" name (perhaps spaces anywhere in the path has a similar issue).

Cheers
Peter

<img width="569" alt="Screen Shot 2022-02-04 at 10 23 11 am" src="https://user-images.githubusercontent.com/92766108/152451698-9c7b89e6-617a-46d4-9972-5e9c85186555.png">

**Comment by pryder-fleetaero** [comment]
Full stack trace of error

<img width="682" alt="Screen Shot 2022-02-04 at 10 28 24 am" src="https://user-images.githubusercontent.com/92766108/152452486-16371ef4-4170-4689-90af-30b51204fc55.png">

**Comment by byohay** [comment]
Hey @pryder-fleetaero! I believe I fixed it in #42.

**Comment by byohay** [comment]
@pryder-fleetaero just released version 0.4.3, LMK if there are any more issues

**Comment by pryder-fleetaero** [comment]
Thanks heaps for that rapid fix. I’ll give it another go in the office tomorrow and advise of any issues. Cheers!

**Comment by pryder-fleetaero** [comment]
Tried it this morning and although my project didn't have any conflicts at the time, it seemed to handle the path spaces OK and correctly reported no conflicts were present.  Thanks again 👍
