### ISSUE TITLE
SPM changes

### ISSUE THREAD

**Issue by pryder-fleetaero** [Lightricks/Kintsugi#49]
I was wondering whether the tool supports resolving a merge conflict containing Swift Package Manager (SPM) conflicts?  In attempting to resolve one of my conflicts it output the following:

Trying to add unsupported component type XCSwiftPackageProductDependency. Full component change is: {"displayName"=>"SnapshotTesting", "isa"=>"XCSwiftPackageProductDependency", "productName"=>"SnapshotTesting", "package"=>{"displayName"=>"https://github.com/pointfreeco/swift-snapshot-testing", "isa"=>"XCRemoteSwiftPackageReference", "repositoryURL"=>"https://github.com/pointfreeco/swift-snapshot-testing", "requirement"=>{"kind"=>"upToNextMajorVersion", "minimumVersion"=>"1.0.0"}}}

I assume this is due to a new SPM dependency having been added in one of the branches.

Cheers
Peter

**Comment by byohay** [comment]
Thanks @pryder-fleetaero! We'll look into it

**Comment by igorkulman** [comment]
Same problem

```
`<PBXNativeTarget name=`ProtonVPN` UUID=`791DE5D8208DDA3000A29EA5`>` attempted to initialize an object with an unknown UUID. `F37F741A27CF7E8C00F1C621` for attribute: `package_product_dependencies`. This can be the result of a merge and the unknown UUID is being discarded.
`<PBXNativeTarget name=`ProtonVPN` UUID=`791DE5D8208DDA3000A29EA5`>` attempted to initialize an object with an unknown UUID. `F37F741A27CF7E8C00F1C621` for attribute: `package_product_dependencies`. This can be the result of a merge and the unknown UUID is being discarded.
Trying to add unsupported component type XCSwiftPackageProductDependency. Full component change is: {"displayName"=>"Search", "isa"=>"XCSwiftPackageProductDependency", "productName"=>"Search"}
```

Looks like as soon as there is some SPM conflict the tool fails.

**Comment by byohay** [comment]
@igorkulman thanks! We'll release a new version that supports SPM changes soon!
