### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by abdlkdrisiktan** [Lightricks/Kintsugi#56]
Hi,

I follow the steps which you guys write in README file, I download Kintsugi successfully
`Successfully installed kintsugi-0.5.0`
`Parsing documentation for kintsugi-0.5.0`
`Done installing documentation for kintsugi after 0 seconds`
`1 gem installed`

after that I run this command `kintsugi MyAppName.xcodeproj/project.pbxproj` but failed. 
Return this  `zsh: command not found: kintsugi`
I refreshed terminal, restart terminal and pc but nothing change I don't know why, 
Can you guys help me ? Did anything do wrong ?

**Comment by ashdnazg** [comment]
Hi, is it possible that your `PATH` environment variable does not include ruby's bin folder?
See [this SO answer](https://stackoverflow.com/a/2392653) for more details.
