### ISSUE TITLE
`apply_change_to_project': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by chrispyballer** [Lightricks/Kintsugi#85]
../.rvm/gems/ruby-2.7.4/gems/kintsugi-0.6.0/lib/kintsugi/apply_change_to_project.rb:40:in `apply_change_to_project': undefined method `[]' for nil:NilClass (NoMethodError)

Getting this ruby syntax error output on some merges.

**Comment by byohay** [comment]
@chrispyballer hey, I was able to reproduce it and fix it in #86

**Comment by chrispyballer** [comment]
Thank you for the great work, @byohay ! This library is saving a lot of people time.
