### ISSUE TITLE
undefined method `children' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by alisandagdelen** [Lightricks/Kintsugi#92]
/Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/apply_change_to_project.rb:857:in `find_file_in_group': undefined method `children' for nil:NilClass (NoMethodError)
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/apply_change_to_project.rb:170:in `apply_file_addition'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/apply_change_to_project.rb:148:in `block in apply_file_changes'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/apply_change_to_project.rb:143:in `each'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/apply_change_to_project.rb:143:in `apply_file_changes'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/apply_change_to_project.rb:66:in `apply_main_group_change'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/apply_change_to_project.rb:46:in `apply_change_to_project'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/merge.rb:93:in `apply_change_and_copy_to_original_path'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/merge.rb:45:in `resolve_conflicts'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi/cli.rb:203:in `block in create_root_command'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/lib/kintsugi.rb:26:in `run'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/gems/kintsugi-0.6.2/bin/kintsugi:10:in `<top (required)>'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/bin/kintsugi:23:in `load'
	from /Users/alisandagdelen/.rvm/gems/ruby-3.0.0@latest/bin/kintsugi:23:in `<main>'

**Comment by byohay** [comment]
Hey @alisandagdelen, I think I was able to reproduce it. I'll submit a fix soon.
Thanks for finding this±

**Comment by byohay** [comment]
@alisandagdelen I think I solved that problem, but unfortunately Kintsugi would still throw in such a case. This is because in "ours" change there's a file addition to a certain group, while in "theirs" change that group was removed.
